const ActionTypes = {
  FOCUS_WINDOW: 'FOCUS_WINDOW',
  ADD_MANIFEST: 'ADD_MANIFEST',
  ADD_WINDOW: 'ADD_WINDOW',
  NEXT_CANVAS: 'NEXT_CANVAS',
  PREVIOUS_CANVAS: 'PREVIOUS_CANVAS',
  REMOVE_WINDOW: 'REMOVE_WINDOW',
  PICK_WINDOWING_SYSTEM: 'PICK_WINDOWING_SYSTEM',
  REQUEST: 'REQUEST_',
  RESOLVE: 'RESOLVE_',
  REJECT: 'REJECT_',
  SET_CONFIG: 'SET_CONFIG',
  UPDATE_CONFIG: 'UPDATE_CONFIG',
};

export default ActionTypes;
